# Use an official Python runtime as a parent image
FROM python:3.6-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Run classification_Sample.py by default when the container launches, unless
# otherwise specified in command line
ENTRYPOINT ["python"]
CMD ["classification_sample.py"]
